In [3]:
import numpy as np



# Criando diferentes arrays



In [23]:
a = [[1,2,3],[3,4,5]]
np.arange(0,10)
cube = np.zeros((3,3)) +9
square = np.ones((2,2))
linear_spaced_array = np.linspace(0,2,10) #10 numeros igualmente separados de 0-2
eye = np.eye(10) #10x10 (0,1)


cube, square, linear_spaced_array, eye

(array([[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]]),
 array([[1., 1.],
        [1., 1.]]),
 array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
        1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ]),
 array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]))

# atributos

In [40]:
np.random.rand(5,5) # 5x5 array de valores aleatórios 
ranarr = np.random.randint (1,100, 10) #tira 10 valores aleatórios de 1-100
ranarr.shape #(10,)
ranarr.reshape(5,2)
ranarr.max()#value
ranarr.argmax() #location

np.int64(4)

In [53]:
#slicing arrays
array_mock = np.random.randint (1,100, 10)
array_mock[:]

array([93, 50, 26, 12,  4, 91, 73, 55, 11,  7])

In [54]:
array_mock[:]*=2
array_mock_copy = array_mock.copy()


array([186, 100,  52,  24,   8, 182, 146, 110,  22,  14])

# slicing

In [59]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
arr_2d.shape
arr_2d[1][2] #6
arr_2d[2][2] #9
arr_2d[:2,1:] #primeiras 2 lin e o que vier dps da 1a col.
''''
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
'''
bool_arr = arr_2d > 4
arr_2d[bool_arr] #se False; não retorna. 
#arr_2d[arr_2d > 4]

array([5, 6, 7, 8, 9])

# operações


In [64]:
arr = np.arange(1,10)
arr = np.sqrt((arr+arr+1)**2)
arr.sum()
#sums across the rows -> .sum(axis='x')
arr.mean()


array([ 3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [66]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

array([1, 3, 5, 7, 9])