In [1]:
import torch
import numpy as np
torch.__version__

'2.5.1'

# Criando Tensors e tensors


In [2]:
arr = np.array([1,2,3,4])
x = torch.from_numpy(arr) #ou torch.as_tensor(arr)
arr.dtype, x.type


(dtype('int64'), <function Tensor.type>)

In [3]:
arr2d = np.arange(0.0,12.0).reshape(4,3)
x2 = torch.from_numpy(arr2d)
x2 #tudo que alterar no arr2d altera em x2 automaticamente


tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [4]:
#caso não queira um link direto:
my_arr2d =  torch.tensor(np.arange(0.0,12.0).reshape(4,3))
my_other_arr2d = torch.tensor(np.arange(0.0,12.0).reshape(4,3)) #qnd eu alterar um deles, td bem


# diferença entre Tensor e tensor

In [7]:
new_arr = np.array([1,2,3]) #array numpy
torch.Tensor(new_arr) #tensor([1., 2., 3.]) --float 
#torch.FloatTensor(new_arr) - mesma coisa - tensor([1., 2., 3.]) --float 
torch.tensor(new_arr) #tensor([1, 2, 3]) --int

tensor([1, 2, 3])

# criando tensdor do scratch


In [31]:
arr = torch.zeros(3,3,3, dtype=torch.int32) 
arr.type(torch.int64) #floating point zeros
#mtos métodos são parecidos 
torch.arange(1,20,2).reshape(5,2) 
torch.linspace(0,18,12).reshape(3,4) 
torch.rand(3,4)
torch.randint(low=0, high=10, size=(3,4))


tensor([[9, 5, 7, 0],
        [7, 8, 9, 7],
        [7, 7, 3, 5]])

In [32]:
torch.manual_seed(10)
torch.rand(1,2)

tensor([[0.4581, 0.4829]])

# indexing e slicing


In [54]:
x = torch.arange(16).reshape(4,4)
y = torch.arange(16).view(4,4) #quase mesma coisa, o que muda é alocacao de memória. View é anterior a reshape
x = x.reshape(16,1)
x = x.reshape(4,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [56]:
x[2:,:]
x.view(4, -1) #-1 -> infere 


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

# Operações


In [64]:
a = torch.arange(3)
b = torch.arange(3)
print(f'{a} \n+\n{b} \n= \n{torch.add(a,b)}')
#a *=b
a.mul_(b)


tensor([0, 1, 2]) 
+
tensor([0, 1, 2]) 
= 
tensor([0, 2, 4])


## multiplicação de matrizes


In [ ]:
# col a  = row b 
torch.mm(a,b) #ou a @ b, mas eh menos recomendado pq @ eh um decorator

In [67]:
#euclidian norm
a = torch.tensor([2., 3., 4., 5.])
a.norm()
#number of elements
a.nelement()

4